### ISSUE TITLE
html5 elements cant be styled by @media print

### ISSUE THREAD

**Issue by paulirish** [aFarkas/html5shiv#68]
Not really a bug in html5 shiv but figure its worth documenting..

just got an email from Jonathan Thérien

>  I just append to found a little annoying bug that people don't seem to be aware.
> 
> IE 7-8 doesn't allow HTML5 element to be styled by a @media print

``` css
@media print {
   html body #side, html body footer, html body header, html body div.filler {
    display:none;
   }
} 
```

> My header and footer were still visible in IE 7-8. Didn't test IE6. Works well in IE9 and other browsers
> 
> I changed to normal DIV are now it work fine. 
> 
> Demo:  http://eld.zoop.net/HTML5_Not_Yet/

If this is true, we should document it somewhere as a limitation that will likely not be worked around.
